# Site settings
title: Greater Technology, for the better.
email: gtech@crlog.info
description: > # this means to ignore newlines until "baseurl:"
  Researching, developing and delivering technology solutions to help better the lives of whose who need it.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://greater.technology" # the base hostname & protocol for your site
twitter_username: gtech
github_username:  zcourts

# Build settings
markdown: kramdown
